// Comprehensive Daily Fitness, Nutrition & Recovery Tips Library for Ultra Gym (200 curated tips)
// Automatically rotates daily based on day of the year.

export interface DailyTip {
  id: number;
  categoryAr: string;
  categoryEn: string;
  tipAr: string;
  tipEn: string;
}

export const DAILY_FITNESS_TIPS: DailyTip[] = [
  // ── 1. الترطيب والأداء الرياضي (1 - 25) ──────────────────────────────
  {
    id: 1,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "احرص على شرب 500 مل من الماء قبل التمرين بنصف ساعة لتجنب الجفاف وتحسين ضخ الدم للعضلات وزيادة قوة التحمل!",
    tipEn: "Drink 500ml of water 30 minutes before training to prevent dehydration, boost blood flow, and enhance muscle endurance!",
  },
  {
    id: 2,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "فقدان 2% فقط من سوائل الجسم أثناء التمرين يقلل من قوتك العضلية وتركيزك بنسبة تصل إلى 15%.",
    tipEn: "Losing just 2% of body fluids during exercise reduces muscular strength and mental focus by up to 15%.",
  },
  {
    id: 3,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "أضف رشة ملح صخري طبيعي مع عصرة ليمون لزجاجة مائك أثناء التمارين الطويلة لتعويض الصوديوم والبوتاسيوم المفقودين بالعرق.",
    tipEn: "Add a pinch of sea salt and lemon to your water during long sessions to replace sodium and potassium lost through sweat.",
  },
  {
    id: 4,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "لون البول الفاتح الشفاف هو أفضل مؤشر يومي على أن جسمك رطب ومستعد لحمل الأوزان بكفاءة.",
    tipEn: "Pale, light-colored urine is the best daily indicator that your body is fully hydrated and primed for heavy lifting.",
  },
  {
    id: 5,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "شرب الماء البارد أثناء التمرين يساعد في خفض درجة حرارة الجسم الداخلية مما يقلل الإجهاد الحراري.",
    tipEn: "Drinking cold water during exercise helps lower core body temperature, delaying thermal fatigue.",
  },
  {
    id: 6,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "لا تعتمد على الشعور بالعطش فقط؛ فالعطش إشارة متأخرة على أن الجفاف قد بدأ بالفعل في التأثير على أدائك.",
    tipEn: "Don't rely solely on thirst; thirst is a delayed signal that dehydration is already hindering performance.",
  },
  {
    id: 7,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "اشرب كوبين من الماء فور الاستيقاظ صباحاً لتنشيط الدورة الدموية وتعويض السوائل المفقودة أثناء 8 ساعات نوم.",
    tipEn: "Drink 2 glasses of water upon waking to kickstart circulation and compensate for fluids lost during 8 hours of sleep.",
  },
  {
    id: 8,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "العضلات تتكون من 75% ماء؛ الجفاف يجعل العضلة تبدو مسطحة وأقل قدرة على توليد القوة الانقباضية.",
    tipEn: "Muscles are 75% water; dehydration makes muscle bellies look flat and weakens contractile force.",
  },
  {
    id: 9,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "تناول ماء جوز الهند الطبيعي بعد التمارين الشاقة يعتبر مصدراً ممتازاً للإلكترولايتات الطبيعية والمغنيسيوم.",
    tipEn: "Natural coconut water post-workout is a fantastic source of natural electrolytes, potassium, and magnesium.",
  },
  {
    id: 10,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "تجنب شرب كميات ضخمة من الماء دفعة واحدة أثناء الراحة بين المجموعات؛ رشفات صغيرة ومستمرة تمنع تلبك المعدة.",
    tipEn: "Avoid chugging huge volumes of water between sets; small, steady sips prevent stomach sloshing and cramping.",
  },
  {
    id: 11,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "في الأيام الحارة، زد استهلاكك المائي بـ 500 إلى 1000 مل إضافية لتعويض التعرق الزائد وحماية الكلى.",
    tipEn: "On hot days, increase water intake by 500-1000ml to offset heavy perspiration and protect kidney function.",
  },
  {
    id: 12,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "الترطيب الجيد يقلل من لزوجة الدم، مما يسمح للقلب بضخ الأكسجين والمغذيات للعضلات بجهد أقل.",
    tipEn: "Proper hydration lowers blood viscosity, allowing your heart to deliver oxygen and nutrients with less strain.",
  },
  {
    id: 13,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "تناول الفواكه الغنية بالماء مثل البطيخ والبرتقال بعد التمرين يوفر ترطيباً خلويًا سريعاً مع سكريات بسيطة للجليكوجين.",
    tipEn: "Hydrating fruits like watermelon and oranges provide fast cellular hydration along with simple carbs for glycogen.",
  },
  {
    id: 14,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "الشاي الأخضر غير المحلى خيار رائع لمضادات الأكسدة وزيادة أكسدة الدهون وترطيب الجسم قبل التمرين.",
    tipEn: "Unsweetened green tea is an excellent choice for antioxidants, fat oxidation support, and pre-workout hydration.",
  },
  {
    id: 15,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "تأكد من شرب لتر ماء على الأقل لكل 1000 سعرة حرارية تستهلكها في نظامك الغذائي اليومي.",
    tipEn: "Aim to drink at least 1 liter of water for every 1,000 calories consumed in your daily diet.",
  },
  {
    id: 16,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "الجفاف يزيد من إفراز هرمون التوتر (الكورتيزول) الذي يسرع هدم النسيج العضلي ويبطئ الاستشفاء.",
    tipEn: "Dehydration spikes the stress hormone cortisol, accelerating muscle breakdown and slowing recovery.",
  },
  {
    id: 17,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "إذا كنت تتناول مكمل الكرياتين، احرص على شرب 3.5 إلى 4 لتر ماء يومياً لضمان تشبع الخلايا العضلية بالسوائل.",
    tipEn: "If using creatine, drink 3.5 to 4 liters of water daily to ensure optimal muscle cell volumization.",
  },
  {
    id: 18,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "السائل الزلالي الذي يزيّت المفاصل ويعمل كوسادة بين العظام يعتمد كلياً على مستوى ترطيب جسمك.",
    tipEn: "Synovial fluid that lubricates joints and cushions cartilage relies directly on your hydration status.",
  },
  {
    id: 19,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "شرب القهوة باعتدال لا يسبب الجفاف كما كان يُعتقد، لكن وازن كل فنجان قهوة بكوب ماء إضافي.",
    tipEn: "Moderate coffee intake doesn't cause dehydration, but balance every cup with an extra glass of water.",
  },
  {
    id: 20,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "الصداع المفاجئ بعد التمرين هو أكثر أعراض نقص الأملاح والسوائل شيوعاً؛ عالجه بالماء والشوارد فوراً.",
    tipEn: "Post-workout headaches are commonly caused by electrolyte depletion; rehydrate with electrolytes right away.",
  },
  {
    id: 21,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "احتفظ بزجاجة ماء بجانبك طوال يوم العمل؛ سهولة الوصول للماء تجعلك تشرب ضعف الكمية المعتادة.",
    tipEn: "Keep a water bottle on your desk; easy visibility and access can double your daily fluid intake.",
  },
  {
    id: 22,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "الشوربات الدافئة الغنية بمرق العظام خيار شتوي مذهل للترطيب وتغذية الأربطة بالكولاجين والأملاح.",
    tipEn: "Bone broth soups in colder months provide excellent hydration along with natural collagen and electrolytes.",
  },
  {
    id: 23,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "الترطيب الليلي المعتدل يمنع الشد العضلي المفاجئ في عضلات الساق (البطات) أثناء النوم.",
    tipEn: "Moderate evening hydration prevents painful nocturnal calf cramps and keeps muscle tissue relaxed.",
  },
  {
    id: 24,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "في التمارين الهوائية المكثفة، اشرب 150-200 مل كل 15 إلى 20 دقيقة للحفاظ على سرعة القلب المستقرة.",
    tipEn: "During intense cardio, drink 150-200ml every 15-20 minutes to maintain steady cardiovascular output.",
  },
  {
    id: 25,
    categoryAr: "الترطيب والأداء",
    categoryEn: "Hydration & Performance",
    tipAr: "ابدأ جلسة تدريبك بجسم رطب مسبقاً، فالترطيب لا يمكن تعويضه في دقائق أثناء أداء المجموعات الثقيلة.",
    tipEn: "Start workouts pre-hydrated; fluid deficits cannot be instantly cured between heavy working sets.",
  },

  // ── 2. البناء العضلي والضخامة (26 - 60) ─────────────────────────────
  {
    id: 26,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تناول ما بين 1.6 إلى 2.2 غرام بروتين لكل كيلوغرام من وزنك يومياً لتحفيز التخليق البروتيني وتسريع الاستشفاء العضلي.",
    tipEn: "Consume 1.6 to 2.2g of protein per kg of body weight daily to maximize muscle protein synthesis and accelerate recovery.",
  },
  {
    id: 27,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "التركيز على النزول البطيء والمتحكم به (Eccentric Phase) يفعّل أليافاً عضلية أعمق ويزيد من الضخامة العضلية بشكل ملحوظ.",
    tipEn: "Focusing on a controlled, slow eccentric (lowering) phase engages deeper muscle fibers and significantly boosts hypertrophy.",
  },
  {
    id: 28,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "الزيادة التدريجية للأحمال (Progressive Overload) هي القانون الأول للبناء العضلي، سواء بزيادة الوزن أو العدات أو تحسين التكنيك.",
    tipEn: "Progressive overload is the golden rule of hypertrophy—achieved by adding weight, reps, or refining technique.",
  },
  {
    id: 29,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "قسم تمرين العضلة الواحدة إلى 10-20 جولة فعالة أسبوعياً للحصول على أفضل توازن بين التحفيز والاستشفاء.",
    tipEn: "Aim for 10 to 20 hard weekly sets per muscle group for the optimal balance between stimulation and recovery.",
  },
  {
    id: 30,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تمرين العضلة مرتين أسبوعياً يعطي نتائج بناء عضلي تفوق تمرينها مرة واحدة بنفس الحجم التدريبي الإجمالي.",
    tipEn: "Training a muscle twice weekly yields superior hypertrophy compared to once weekly at the same total volume.",
  },
  {
    id: 31,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تمرين العضلة في أقصى تمدد لها (Stretched Position) يعطي أقوى إشارة حيوية للبناء العضلي مقارنة بنصف المدى.",
    tipEn: "Training a muscle in its fully stretched position produces a stronger hypertrophy signal than half-rep movements.",
  },
  {
    id: 32,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "الراحة لمدة دقيقتين إلى 3 دقائق بين المجموعات المركبة تسمح باستعادة طاقة ATP ورفع أوزان أثقل بجودة أعلى.",
    tipEn: "Resting 2-3 minutes between compound sets allows ATP restoration, enabling higher quality, heavier sets.",
  },
  {
    id: 33,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "التركيز الذهني الواعي على انقباض العضلة المستهدفة (Mind-Muscle Connection) يزيد من التفعيل العصبي بنسبة تصل إلى 20%.",
    tipEn: "Consciously focusing on contracting the target muscle increases neuromuscular activation by up to 20%.",
  },
  {
    id: 34,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "لا تجعل كل مجموعة تنتهي بالفشل العضلي التام؛ اترك عدة أو عدتين في الاحتياط (RIR 1-2) لضمان جودة بقية التمرين.",
    tipEn: "Don't take every set to total failure; leave 1-2 reps in reserve (RIR) to preserve central nervous system energy.",
  },
  {
    id: 35,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "التمارين المركبة (سكوات، ديدليفت، بنش برس، عقلة) تبني الأساس العضلي وتفرز هرمونات بنائية أعلى من تمارين العزل.",
    tipEn: "Compound lifts (Squats, Deadlifts, Bench, Pull-ups) build dense muscle mass and stimulate greater hormonal response.",
  },
  {
    id: 36,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تغيير التمارين كل أسبوع يمنعك من قياس التقدم؛ التزم بنفس الجدول الأساسي لـ 8 إلى 12 أسبوعاً قبل تغييره.",
    tipEn: "Changing exercises every week prevents measuring progress; stick to core lifts for 8-12 weeks to master them.",
  },
  {
    id: 37,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "حمض الليوسين (Leucine) في البروتين هو المفتاح الحيوي لتفعيل مسار mTOR المسؤول عن إطلاق إشارة بناء العضلات.",
    tipEn: "Leucine in protein is the critical trigger that activates the mTOR pathway responsible for initiating muscle growth.",
  },
  {
    id: 38,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "المدى الحركي الكامل (Full ROM) يتفوق على الأوزان الزائدة مع نصف مدى في تحفيز الألياف وحماية الأوتار.",
    tipEn: "Full range of motion beats ego-lifting heavy weights with partial reps for muscle activation and joint safety.",
  },
  {
    id: 39,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "فائض السعرات المعتدل (200-300 سعرة فوق احتياجك) يضمن بناء عضلات صافية بدون تراكم دهون غير مرغوبة.",
    tipEn: "A slight caloric surplus (200-300 kcal above maintenance) supports clean lean muscle gains with minimal fat gain.",
  },
  {
    id: 40,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تمارين العزل (Isolation) مثل الرفرفة والبايسبس ضرورية لسد نقاط الضعف ونحت تفاصيل العضلة بدقة.",
    tipEn: "Isolation exercises like lateral raises and curls are essential for refining weak points and muscle detail.",
  },
  {
    id: 41,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تثبيت الكوع والكتف أثناء تمارين الذراعين يمنع انتقال الحمل للمفاصل ويجبر العضلة المستهدفة على العمل بمفردها.",
    tipEn: "Locking your elbows and shoulders during arm exercises prevents momentum and isolates the target muscle.",
  },
  {
    id: 42,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "سرعة رفع الوزن (Concentric) يجب أن تكون متفجرة وقوية، بينما الهبوط يكون بطيئاً وتحت السيطرة.",
    tipEn: "Lift explosively on the concentric phase, and lower with controlled tempo on the eccentric phase.",
  },
  {
    id: 43,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "التنوع في نطاق العدات (6-8 للقوة، 8-12 للضخامة، 12-15 للتحمل) يستهدف كل أنواع الألياف العضلية السريعة والبطيئة.",
    tipEn: "Varying rep ranges (6-8 for strength, 8-12 for size, 12-15 for endurance) targets both Type I and Type II fibers.",
  },
  {
    id: 44,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "أسبوع تفريغ الأحمال (Deload Week) كل 6-8 أسابيع يجدد الجهاز العصبي والأربطة ويمنع ثبات الأوزان.",
    tipEn: "A deload week every 6-8 weeks resets your nervous system, relieves joints, and prevents strength plateaus.",
  },
  {
    id: 45,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "عضلات الظهر الكبيرة تحتاج زوايا سحب متعددة (سحب عمودي للاتساع وسحب أفقي للسماكة).",
    tipEn: "Complete back development requires multiple angles: vertical pulls for width, and horizontal rows for thickness.",
  },
  {
    id: 46,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تمرين الأرجل القوي يحفز الدورة الدموية في كامل الجسم ويزيد إفراز هرمون التستوستيرون الطبيعي.",
    tipEn: "Heavy leg training stimulates systemic blood circulation and triggers natural testosterone and GH release.",
  },
  {
    id: 47,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "الاستقرار في القبضة وقوة السواعد يزيد تلقائياً من قدرتك على حمل أوزان أثقل في كافة تمارين السحب.",
    tipEn: "Developing a strong grip and forearm strength directly increases your pulling strength in rows and deadlifts.",
  },
  {
    id: 48,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "استخدم أحزمة المعصم (Straps) في مجموعات السحب الثقيلة حتى لا تكون قبضة يدك هي العائق قبل تعب الظهر.",
    tipEn: "Use lifting straps on heavy back sets so grip fatigue doesn't limit back muscle stimulation.",
  },
  {
    id: 49,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "عضلة الترايسبس تشكل 60% من حجم الذراع الإجمالي؛ ركز على تمارين الرأس الطويل مثل الترايسبس فوق الرأس.",
    tipEn: "Triceps make up 60% of total arm size; emphasize the long head with overhead extension movements.",
  },
  {
    id: 50,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "التوقف لثانية واحدة عند قمة الانقباض العضلي (Peak Contraction) يزيد من ضخ الدم ويمنحك إحساساً عميقاً بالعضلة.",
    tipEn: "Pausing for 1 second at peak contraction maximizes blood pump and intensifies muscle fiber recruitment.",
  },
  {
    id: 51,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تمارين الكيبل تحافظ على ضغط وتوتر مستمر (Constant Tension) على العضلة طوال مسار الحركة مقارنة بالدمبلز.",
    tipEn: "Cable exercises maintain constant mechanical tension across the entire range of motion compared to free dumbbells.",
  },
  {
    id: 52,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "عضلات البطن تبنى في الجيم بأوزان ومقاومة، ولكن تظهر في المطبخ بنسبة دهون منخفضة.",
    tipEn: "Abs are built in the gym with progressive resistance, but revealed in the kitchen via low body fat.",
  },
  {
    id: 53,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "توزيع وجبات البروتين على 3 إلى 5 وجبات يومياً يضمن استمرار إشارات البناء العضلي على مدار 24 ساعة.",
    tipEn: "Distributing protein across 3 to 5 meals daily keeps muscle protein synthesis elevated around the clock.",
  },
  {
    id: 54,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تجنب الإفراط في مدة التمرين (أكثر من 75 دقيقة) لتفادي ارتفاع الكورتيزول وهبوط الطاقة الحاد.",
    tipEn: "Avoid training longer than 75 minutes to prevent excessive cortisol spikes and severe energy depletion.",
  },
  {
    id: 55,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "التمارين أحادية الجانب (Unilateral) مثل الطعنات والدمبل الفردي تعالج عدم التماثل العضلي بين الجانبين.",
    tipEn: "Unilateral exercises (lunges, single-arm presses) fix strength imbalances and promote symmetric development.",
  },
  {
    id: 56,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "عضلات الصدر العلوية تعطي مظهراً ممتلئاً وقوياً؛ ابدأ جلسة الصدر بتمارين الإنكلاين (Incline Press).",
    tipEn: "Upper chest creates a full, dense physique; prioritize incline pressing at the start of chest workouts.",
  },
  {
    id: 57,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "الاستمرارية لمدة 6 أشهر بدون انقطاع أهم من التدريب العنيف لمدة شهرين ثم التوقف.",
    tipEn: "6 months of consistent, disciplined training beats 2 months of extreme training followed by quitting.",
  },
  {
    id: 58,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "تتبع وزنك وقياساتك وصورك الشهرية بدقة؛ المرآة والميزان معاً يعكسان تطور الكتلة العضلية الحقيقي.",
    tipEn: "Track monthly measurements, weight, and progress photos; visual data reveals real body recomposition.",
  },
  {
    id: 59,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "الإحساس بالحرقة العضلية ناتج عن تراكم أيونات الهيدروجين، وهو مؤشر على الإجهاد الأيضي المحفز للنمو.",
    tipEn: "The muscle burn is caused by hydrogen ion accumulation and indicates metabolic stress that triggers growth.",
  },
  {
    id: 60,
    categoryAr: "البناء العضلي",
    categoryEn: "Muscle Building",
    tipAr: "أقوى حافز للبناء العضلي هو التوتر الميكانيكي (Mechanical Tension) الناتج عن رفع أوزان حقيقية بتكنيك صارم.",
    tipEn: "Mechanical tension from lifting challenging weights with strict form is the primary driver of muscle hypertrophy.",
  },

  // ── 3. التغذية والماكروز والسعرات (61 - 95) ─────────────────────────
  {
    id: 61,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "وجبة كربوهيدرات معقدة مع بروتين خفيف (مثل الموز والشوفان) قبل التمرين بساعتين تمنحك طاقة ثابتة وتمنع الهبوط المفاجئ.",
    tipEn: "A complex carb meal with lean protein (like oats & banana) 2 hours before training provides sustained energy without crashes.",
  },
  {
    id: 62,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الجمع بين البروتين السريع والكربوهيدرات بعد التمرين يعيد تعبئة مخازن الجليكوجين ويوقف الهدم العضلي فوراً.",
    tipEn: "Pairing fast-digesting protein with carbs after training restores muscle glycogen and halts catabolism immediately.",
  },
  {
    id: 63,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الدهون الصحية (زيت زيتون، مكسرات، أفوكادو) ضرورية لإنتاج هرمونات الجسم الأساسية وامتصاص فيتامينات A, D, E, K.",
    tipEn: "Healthy fats (olive oil, nuts, avocado) are vital for endocrine hormone synthesis and fat-soluble vitamin absorption.",
  },
  {
    id: 64,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تناول مصادر بروتين عالية القيمة الحيوية مثل البيض، صدور الدجاج، اللحم البقري الصافي، والأسماك.",
    tipEn: "Prioritize high biological value protein sources like whole eggs, chicken breasts, lean beef, and wild fish.",
  },
  {
    id: 65,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "احسب سعراتك بدقة لمدة أسبوعين على الأقل لتتعرف على أحجام الحصص الحقيقية وتفهم استهلاكك الفعلي.",
    tipEn: "Weigh and track your food for at least 2 weeks to learn accurate portion sizes and understand actual caloric intake.",
  },
  {
    id: 66,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الكربوهيدرات ليست عدوك! هي الوقود الأساسي للجهاز العصبي والعضلات أثناء التمارين ذات الشدة العالية.",
    tipEn: "Carbohydrates are not the enemy; they are the primary fuel for your central nervous system and high-intensity lifting.",
  },
  {
    id: 67,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تناول 25-35 غرام من الألياف يومياً يحسن صحة الميكروبيوم المعوي ويحافظ على استقرار مستويات السكر في الدم.",
    tipEn: "Consuming 25-35g of fiber daily supports gut microbiome health and stabilizes blood glucose levels.",
  },
  {
    id: 68,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "البيض الكامل يحتوي على الكولين وفيتامينات ب والدهون الصحية التي تعزز تخليق البروتين أفضل من بياض البيض بمفرده.",
    tipEn: "Whole eggs contain choline and healthy lipids that enhance muscle protein synthesis compared to egg whites alone.",
  },
  {
    id: 69,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "وجبة قبل النوم الغنية ببروتين الكازين البطيء الامتصاص (مثل الجبن القريش أو الزبادي اليوناني) تغذي عضلاتك طوال الليل.",
    tipEn: "A pre-bed meal rich in slow-digesting casein (cottage cheese, Greek yogurt) provides sustained amino acid release all night.",
  },
  {
    id: 70,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تجنب الوجبات الدسمة جداً قبل التمرين مباشرة؛ هضم الدهون يستغرق وقتاً طويلاً ويسحب الدم من العضلات للمعدة.",
    tipEn: "Avoid high-fat meals right before workouts; fat digestion takes hours and diverts blood from working muscles.",
  },
  {
    id: 71,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الطهي بالمنزل هو السر الأكبر للتحكم في كميات الزيوت والصوديوم والسعرات الخفية.",
    tipEn: "Cooking at home is the single most effective way to eliminate hidden oils, excessive sodium, and sneaky calories.",
  },
  {
    id: 72,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تناول الخضروات الملونة يمدك بمضادات الأكسدة التي تقلل الإجهاد التأكسدي بعد التمارين الرياضية القوية.",
    tipEn: "Eating a colorful variety of vegetables provides polyphenols that combat post-exercise oxidative stress.",
  },
  {
    id: 73,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الشوفان يحتوي على ألياف البيتا جلوكان التي تخفض الكوليسترول الضار وتمنحك شبعاً طويلاً وثابتاً.",
    tipEn: "Oats contain beta-glucan fiber that lowers LDL cholesterol and provides long-lasting, steady satiety.",
  },
  {
    id: 74,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الأسماك الدهنية مثل السلمون والتونة تمدك بجرعة قوية من أوميغا 3 والبروتين الكامل في وجبة واحدة.",
    tipEn: "Fatty fish like salmon and tuna deliver a powerful combination of omega-3s and complete protein in one meal.",
  },
  {
    id: 75,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "لا تحذف مجموعة غذائية كاملة بدون سبب طبي؛ التوازن المستدام هو ما يجعلك تستمر لسنوات وليس لأسابيع.",
    tipEn: "Never eliminate entire food groups without medical need; flexible sustainability is the secret to lifelong fitness.",
  },
  {
    id: 76,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "المشروبات المحلاة والعصائر المعلبة سعرات سائلة خالية من الشبع؛ استبدلها بالماء أو المشروبات الخالية من السكر.",
    tipEn: "Sugary drinks and juices are empty liquid calories with zero satiety; swap them for water or zero-calorie drinks.",
  },
  {
    id: 77,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الملح الطبيعي ليس عدوك؛ الرياضيون يحتاجون الصوديوم لنقل الإشارات العصبية وانقباض العضلات بكفاءة.",
    tipEn: "Natural salt is essential for lifters; sodium is required for nerve transmission and forceful muscle contractions.",
  },
  {
    id: 78,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تناول البروتين أولاً في وجبتك يساعد على تقليل الشهية وضبط إفراز هرمون الجريلين المسؤول عن الجوع.",
    tipEn: "Eating your protein portion first increases satiety signals and regulates the hunger hormone ghrelin.",
  },
  {
    id: 79,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "البطاطا والبطاطس المسلوقة من أكثر الأطعمة تصدراً لمؤشر الشبع العالمي، وهي مصدر طاقة رائع للرياضيين.",
    tipEn: "Boiled potatoes rank #1 on the global satiety index, making them a fantastic clean carb source for lifters.",
  },
  {
    id: 80,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الزبادي اليوناني يحتوي على ضعف كمية البروتين مقارنة بالزبادي العادي، وهو غني بالبروبيوتيك لصحة الأمعاء.",
    tipEn: "Greek yogurt packs double the protein of regular yogurt along with gut-healthy live probiotic cultures.",
  },
  {
    id: 81,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "احرص على أخذ قياساتك وسعراتك على مدار المتوسط الأسبوعي وليس يوماً بيوم لتفادي تذبذب السوائل.",
    tipEn: "Assess your weight and calories based on weekly averages rather than single-day fluctuations.",
  },
  {
    id: 82,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الأرز الأبيض سهل الهضم وسريع الامتصاص كوجبة كربوهيدرات نظيفة ومثالية حول أوقات التمرين.",
    tipEn: "White rice is easily digestible and fast-absorbing, making it a staple peri-workout carbohydrate source.",
  },
  {
    id: 83,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "المكسرات النيئة وجبة خفيفة ممتازة للمغنيسيوم والدهون الأحادية، لكن انتبه لكمياتها لأنها عالية السعرات.",
    tipEn: "Raw nuts provide great magnesium and monounsaturated fats, but weigh portions as calories add up quickly.",
  },
  {
    id: 84,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تجهيز وجباتك مسبقاً (Meal Prep) يوفر وقتك ويحميك من اتخاذ خيارات طعام عشوائية عند الشعور بالجوع الشديد.",
    tipEn: "Meal prepping saves time and prevents impulsive poor food choices when intense hunger strikes.",
  },
  {
    id: 85,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "التوابل الطبيعية مثل الكركم والزنجبيل والقرفة تضيف نكهة رائعة وتملك خصائص مضادة للالتهابات وتحسن حساسية الإنسولين.",
    tipEn: "Natural spices like turmeric, ginger, and cinnamon add flavor while fighting inflammation and boosting insulin sensitivity.",
  },
  {
    id: 86,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تناول وجبة متوازنة تحتوي على البروتين والكربوهيدرات خلال ساعتين بعد التمرين هو النافذة الأفضل لإعادة البناء.",
    tipEn: "Consuming a balanced meal with protein and carbs within 2 hours post-workout maximizes anabolic remodeling.",
  },
  {
    id: 87,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "القرفة تساعد في خفض مستويات السكر في الدم بعد الوجبات وتحسن نقل الجلوكوز إلى الخلايا العضلية.",
    tipEn: "Cinnamon helps blunt post-meal blood glucose spikes and enhances glucose uptake into muscle cells.",
  },
  {
    id: 88,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "بذور الشيا والكتان غنية بألياف الميوسيلاجين وأوميغا 3 النباتية التي تدعم مرونة المفاصل وصحة القلب.",
    tipEn: "Chia and flaxseeds deliver soluble mucilage fiber and plant-based ALA omega-3s for joint and heart health.",
  },
  {
    id: 89,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "احذر من أطعمة 'الدايت' التجارية المليئة بالمحليات الصناعية والدهون المهدرجة؛ اختر الطعام الحقيقي دائماً.",
    tipEn: "Beware of processed 'diet' labeled foods; prioritize single-ingredient, unprocessed whole foods.",
  },
  {
    id: 90,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "تناول مصادر فيتامين C مثل الفلفل الرومي والكيوي يساعد في بناء الكولاجين اللازم لتقوية الأوتار والغضاريف.",
    tipEn: "Vitamin C-rich foods like bell peppers and kiwi are essential co-factors for collagen synthesis in tendons.",
  },
  {
    id: 91,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "التغذية الذكية تمثل 70% من رحلة التحول الجسدي؛ لا يمكنك التغلب على نظام غذائي سيء بالتمارين وحدها.",
    tipEn: "Smart nutrition is 70% of physical transformation; you cannot out-train a chronically poor diet.",
  },
  {
    id: 92,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الجبن الأبيض قليل الملح والموز يعتبران وجبة خفيفة غنية بالبوتاسيوم والكالسيوم لمنع التقلصات العضلية.",
    tipEn: "Low-salt white cheese and a banana make a quick snack loaded with potassium and calcium to prevent cramps.",
  },
  {
    id: 93,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "الموز الناضج قبل التمرين يوفر كربوهيدرات سريعة الامتصاص لرفع الطاقة الفورية خلال 20 دقيقة.",
    tipEn: "A ripe banana 20 minutes before training provides readily available glucose for immediate energy output.",
  },
  {
    id: 94,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "المضغ الجيد والبطيء للطعام يحسن إفراز الإنزيمات الهاضمة ويمنع الانتفاخ والغازات بعد الوجبات الكبيرة.",
    tipEn: "Chewing food thoroughly enhances digestive enzyme secretion and prevents post-meal bloating and gas.",
  },
  {
    id: 95,
    categoryAr: "التغذية والماكروز",
    categoryEn: "Nutrition & Macros",
    tipAr: "قاعدة 80/20: اجعل 80% من طعامك من مصادر طبيعية كاملة، و20% مرونة لتستمتع بحياتك دون شعور بالحرمان.",
    tipEn: "The 80/20 rule: Eat 80% wholesome nutrient-dense foods, and leave 20% flexibility for sustainable adherence.",
  },

  // ── 4. الاستشفاء والنوم وصحة الجهاز العصبي (96 - 125) ───────────────────
  {
    id: 96,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "العضلات لا تنمو في الجيم بل أثناء النوم العميق (7-9 ساعات)! هرمون النمو يفرز بأعلى معدلاته في أول 4 ساعات من النوم.",
    tipEn: "Muscles grow during deep sleep (7-9 hours), not in the gym! Growth hormone reaches peak secretion during the first 4 hours of sleep.",
  },
  {
    id: 97,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "أغلق الشاشات والهواتف قبل النوم بـ 45 دقيقة؛ الضوء الأزرق يثبط إفراز هرمون الميلاتونين المسؤول عن النعاس والراحة.",
    tipEn: "Turn off screens 45 minutes before bed; blue light suppresses melatonin release and disrupts restorative deep sleep.",
  },
  {
    id: 98,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "درجة حرارة الغرفة المثالية للنوم العميق هي بين 18 إلى 20 درجة مئوية؛ البرودة المعتدلة تخفض ضربات القلب وتعمق النوم.",
    tipEn: "The optimal room temperature for deep sleep is 18-20°C (65-68°F); cool ambient air lowers heart rate and deepens sleep.",
  },
  {
    id: 99,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "في أيام الراحة، المشي لـ 30 دقيقة يحفز تدفق الدم للمفاصل ويطرد حمض اللاكتيك المتراكم لتستيقظ نشيطاً في اليوم التالي.",
    tipEn: "On rest days, a 30-minute walk boosts blood flow and flushes lactic acid, helping you feel refreshed for your next workout.",
  },
  {
    id: 100,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "الاستحمام بالماء الدافئ قبل النوم بـ 60 دقيقة يساعد الأوعية الدموية على التمدد ويحفز الاسترخاء العضلي السريع.",
    tipEn: "A warm shower 60 minutes before bed promotes vasodilation and prepares muscles and the nervous system for sleep.",
  },
  {
    id: 101,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "الجهاز العصبي المركزي (CNS) يستغرق وقتاً أطول للاستشفاء من الألياف العضلية بعد تمارين السكوات والديدليفت الثقيلة.",
    tipEn: "The central nervous system (CNS) takes longer to recover than muscle tissue after heavy squats and deadlifts.",
  },
  {
    id: 102,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "جلسة ساونا لمدة 15-20 دقيقة بعد التمرين تنشط بروتينات الصدمة الحرارية (Heat Shock Proteins) التي تسرع التعافي.",
    tipEn: "A 15-20 minute sauna session post-workout activates heat shock proteins (HSPs) that accelerate cellular repair.",
  },
  {
    id: 103,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "المغنيسيوم بيسجلايسينات (Magnesium Bisglycinate) قبل النوم يهدئ المستقبلات العصبية ويرخي الألياف المشدودة.",
    tipEn: "Magnesium Bisglycinate before bed calms neural excitability and relaxes tight, contracted muscle fibers.",
  },
  {
    id: 104,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "تجنب تناول الكافيين بعد الساعة 4 مساءً، حيث يمتلك الكافيين عمراً نصفياً يصل إلى 6-8 ساعات في مجرى الدم.",
    tipEn: "Avoid caffeine after 4 PM; caffeine has a 6-8 hour half-life that can severely impair sleep architecture.",
  },
  {
    id: 105,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "تمارين التنفس البطني العميق (4 ثواني شهيق، 7 ثواني حبس، 8 ثواني زفير) تخفض هرمون التوتر وتنقلك للطور الباراسمبثاوي.",
    tipEn: "Deep 4-7-8 diaphragmatic breathing downregulates stress and activates the parasympathetic recovery state.",
  },
  {
    id: 106,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "قيلولة قصيرة لمدة 20 دقيقة في منتصف النهار تعيد شحن التركيز الذهني وتعوض جزءاً من نقص النوم الليلي.",
    tipEn: "A 20-minute power nap midday restores cognitive sharpness and helps mitigate partial sleep debt.",
  },
  {
    id: 107,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "استخدام الفوم رولر (Foam Roller) لمدة 5 دقائق بعد التمرين يفك الالتصاقات الليفية (Myofascial Release) ويحسن المرونة.",
    tipEn: "5 minutes of foam rolling post-workout releases myofascial adhesions and improves soft tissue mobility.",
  },
  {
    id: 108,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "النوم في ظلام تام يحفز الغدة الصنوبرية على إفراز أعلى تركيز من هرمون الميلاتونين ومضادات الأكسدة الليلية.",
    tipEn: "Sleeping in pitch-black darkness maximizes pineal melatonin secretion and nighttime cellular repair.",
  },
  {
    id: 109,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "ألم العضلات المتأخر (DOMS) بعد 24-48 ساعة طبيعي، لكن استمراره لأكثر من 4 أيام يشير إلى نقص التغذية أو النوم.",
    tipEn: "Delayed onset muscle soreness (DOMS) for 24-48 hours is normal; lasting over 4 days signals under-recovery.",
  },
  {
    id: 110,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "الاستماع لجسمك عند الشعور بالإرهاق الحاد وأخذ يوم راحة إضافي يحميك من الإصابات المزمنة التي توقفك لأشهر.",
    tipEn: "Listening to acute fatigue and taking an extra rest day prevents chronic injuries that sideline you for months.",
  },
  {
    id: 111,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "الحفاظ على موعد نوم واستيقاظ ثابت يومياً حتى في عطلة نهاية الأسبوع يضبط ساعتك البيولوجية وهرموناتك.",
    tipEn: "Keeping a consistent sleep and wake schedule, even on weekends, locks in your circadian rhythm and hormone balance.",
  },
  {
    id: 112,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "التعرض لضوء الشمس الطبيعي في أول 30 دقيقة من الاستيقاظ يرفع هرمون اليقظة ويساعدك على النوم بسهولة ليلاً.",
    tipEn: "Getting natural sunlight within 30 minutes of waking sets your internal clock and promotes easy sleep at night.",
  },
  {
    id: 113,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "التدليك العضلي الرياضي (Sports Massage) مرة شهرياً يحسن تروية الأنسجة العميقة ويحرر العقد العضلية.",
    tipEn: "A monthly sports massage improves deep tissue perfusion and breaks up persistent muscle knots.",
  },
  {
    id: 114,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "تناول وجبة عشاء خفيفة قبل النوم بساعتين يمنع عسر الهضم والارتجاع المريئي الذي يقطع مراحل النوم العميق.",
    tipEn: "Finishing a light dinner 2 hours before bed prevents indigestion and acid reflux from disrupting deep sleep cycles.",
  },
  {
    id: 115,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "التأمل والاسترخاء الذهني لـ 10 دقائق يومياً يقلل مستويات الالتهاب الجهازي ويحسن سرعة الاستشفاء.",
    tipEn: "10 minutes of daily mindfulness or meditation lowers systemic inflammation and accelerates nervous system recovery.",
  },
  {
    id: 116,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "تجنب التمارين العنيفة جداً قبل النوم مباشرة (أقل من ساعتين) لأنها ترفع حرارة الجسم والكورتيزول وتؤخر النوم.",
    tipEn: "Avoid intense lifting right before bed; elevated body temperature and cortisol delay the onset of sleep.",
  },
  {
    id: 117,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "الاستشفاء ليس رفاهية؛ هو النصف المكمل للتدريب وبدونه لا تحدث أي تكيفات عضلية أو تقدم في الأداء.",
    tipEn: "Recovery is not a luxury; it is 50% of the muscle equation and where actual physical adaptation happens.",
  },
  {
    id: 118,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "ارتداء ملابس نوم قطنية مريحة واستخدام وسادة تدعم فقرات الرقبة يمنع تشنج عضلات الترابيس والكتفين.",
    tipEn: "Breathable sleepwear and an ergonomic pillow prevent neck strain and upper trapezius stiffness upon waking.",
  },
  {
    id: 119,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "مشروب البابونج أو اللافندر الدافئ قبل النوم خيار طبيعي ممتاز لتهدئة الأعصاب وتخفيف التوتر العضلي.",
    tipEn: "Warm chamomile or lavender herbal tea before bed naturally soothes the nervous system and eases muscular tension.",
  },
  {
    id: 120,
    categoryAr: "النوم والاستشفاء",
    categoryEn: "Sleep & Recovery",
    tipAr: "تخصيص يوم كامل أسبوعياً للراحة التامة من الأثقال والرياضة يمنح عقلك وجسدك تجديداً شاملاً للشغف والطاقة.",
    tipEn: "Scheduling one complete rest day each week from all lifting revitalizes mental passion and physical drive.",
  },

  // ── 5. التكنيك وسلامة المفاصل والعمود الفقري (121 - 150) ──────────────
  {
    id: 121,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "خذ نفساً عميقاً في البطن (Valsalva Maneuver) أثناء رفع الأوزان الثقيلة لتثبيت العمود الفقري وحماية أسفل الظهر.",
    tipEn: "Brace your core with a deep belly breath (Valsalva Maneuver) during heavy lifts to protect your spine and maximize stability.",
  },
  {
    id: 122,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمرين السكوات، ادفع ركبتيك للخارج باتجاه اتجاه أصابع القدمين وتجنب انطباق الركبتين للداخل (Knee Valgus).",
    tipEn: "During squats, track knees outward in line with toes; never allow your knees to cave inward (Knee Valgus).",
  },
  {
    id: 123,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمرين البنش برس، احرص على ضم لوحي الكتف للخلف والأسفل (Scapular Retraction) لحماية مفصل الكتف من التمزق.",
    tipEn: "In bench press, retract and depress your shoulder blades into the bench to protect the delicate rotator cuff.",
  },
  {
    id: 124,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "تجنب تقويس أسفل الظهر بشكل مفرط في تمرين الديدليفت؛ حافظ على استقامة العمود الفقري كقطعة واحدة صلبة.",
    tipEn: "Avoid rounding or hyper-extending your lower back in deadlifts; maintain a neutral, rigid spine throughout the lift.",
  },
  {
    id: 125,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "الإحماء بمجموعات تصاعدية خفيفة قبل الوزن الأساسي يجهز المسارات العصبية ويزيّت المفاصل بالسوائل.",
    tipEn: "Pyramid warm-up sets with light weights prime neuromuscular pathways and lubricate joints before working weights.",
  },
  {
    id: 126,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمرين السحب للظهر (Lat Pulldown)، اسحب بكوعيك للأسفل باتجاه الخصر وليس بسحب يديك فقط لتفعيل عضلات اللاتس.",
    tipEn: "In Lat Pulldowns, drive down through your elbows toward your hips rather than pulling solely with your hands.",
  },
  {
    id: 127,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "تجنب فرد مفصل الركبة أو الكوع بشكل كامل ومقفل (Lockout) في أجهزة الدفع لحماية الغضاريف من الصدمات.",
    tipEn: "Avoid hyper-locking knees or elbows on heavy press machines to keep stress on muscle fibers rather than joint cartilage.",
  },
  {
    id: 128,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "ارتدِ حذاءً ذا نعل مسطح وصلب في تمارين الأرجل والديدليفت لضمان قاعدة ارتكاز ثابتة ونقل طاقة فعال من الأرض.",
    tipEn: "Wear flat, solid-soled shoes for squats and deadlifts to ensure a stable base and efficient ground force transfer.",
  },
  {
    id: 129,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "تمارين الروتاتور كاف (Rotator Cuff) بالأوزان الخفيفة تقوي أوتار الكتف وتمنع إصابات الاصطدام (Impingement).",
    tipEn: "Light rotator cuff external rotations strengthen stabilizer tendons and prevent painful shoulder impingement.",
  },
  {
    id: 130,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "عند رفع الأوزان من الأرض لوضعية البداية، ارفعها بثني الركبتين واستخدام قوة الأرجل وليس بانحناء الظهر.",
    tipEn: "When picking up dumbbells from the floor, bend your knees and lift with your legs, never with a rounded spine.",
  },
  {
    id: 131,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمرين الرفرفة الجانبية للكتف، اجعل حركة ذراعيك في مستوى لوح الكتف (Scapular Plane) بزاوية 30 درجة للأمام قليلاً.",
    tipEn: "Perform lateral raises in the scapular plane (angled ~30° forward) to eliminate shoulder joint pinching.",
  },
  {
    id: 132,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "لا ترفع وزناً يجعلك تهتز أو تستعين بمرجحة الجسم؛ التكنيك النظيف مع وزن معقول يبني عضلات أسرع ويحميك من الإصابة.",
    tipEn: "Never lift weights that force excessive body swinging; strict execution builds muscle faster and prevents injuries.",
  },
  {
    id: 133,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "حافظ على وضعية الرقبة المحايدة أثناء التمرين؛ انظر لنقطة ثابتة أمامك وتجنب رفع رأسك لأعلى في الديدليفت.",
    tipEn: "Keep your cervical spine neutral; fix your gaze ahead and avoid cranking your neck upward during deadlifts.",
  },
  {
    id: 134,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "استخدم حزام الأمان (Lifting Belt) كأداة لزيادة الضغط داخل البطن في المجموعات الثقيلة جداً (85%+ من أقصى وزن).",
    tipEn: "Use a lifting belt on heavy 85%+ 1RM sets as a tactile cue to generate maximum intra-abdominal pressure.",
  },
  {
    id: 135,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "مرونة مفصل الكاحل (Ankle Mobility) هي العامل الحاسم للنزول بعمق كافٍ في السكوات دون تقوس أسفل الظهر.",
    tipEn: "Ankle dorsiflexion mobility is the secret to squatting deep without experiencing lower back butt-wink.",
  },
  {
    id: 136,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمارين الضغط بالدمبل، حافظ على زاوية الكوع بـ 45-60 درجة مع الجذع وتجنب فتح الكوعين بـ 90 درجة.",
    tipEn: "In dumbbell presses, tuck elbows at a 45-60° angle to your torso; never flare elbows out to a 90° angle.",
  },
  {
    id: 137,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "إذا شعرت بألم حاد في المفصل أثناء أداء تمرين معين، توقف فوراً وغيّر الزاوية أو الجهاز؛ الألم الحاد ليس ألماً عضلياً.",
    tipEn: "If you feel sharp joint pain during a lift, stop immediately and adjust angles; sharp pain is never muscle fatigue.",
  },
  {
    id: 138,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "تثبيت القدمين بالكامل على الأرض (Tripod Foot: الكعب وقاعدة الإبهام والخنصر) يمنحك توازناً وقوة دفع جبارة.",
    tipEn: "Maintain a tripod foot (heel, big toe, pinky toe grounded) for rock-solid stability and maximum leg drive.",
  },
  {
    id: 139,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمرين الهيب ثرست (Hip Thrust)، ادفع من خلال الكعبين واعتمد على انقباض المؤخرة الكامل دون تقويس أسفل الظهر.",
    tipEn: "In hip thrusts, drive through heels and achieve full glute lockout without over-arching the lumbar spine.",
  },
  {
    id: 140,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "حافظ على توازي المعصم مع الساعد أثناء حمل البار وتجنب ثني المعصم للخلف لحماية الأعصاب والأوتار.",
    tipEn: "Keep wrists stacked straight over forearms when pressing to prevent excessive wrist strain and tendonitis.",
  },
  {
    id: 141,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "تمارين الإطالة الحركية للورك (Hip Openers) قبل تمرين الأرجل تحرر الحوض وتسمح بحركة سلسة خالية من الآلام.",
    tipEn: "Dynamic hip opening drills before leg day free up pelvic tilt and allow smooth, pain-free squat depth.",
  },
  {
    id: 142,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمارين السحب الأرضي (Barbell Row)، ثبّت زاوية جذعك واعتمد على سحب الظهر وتجنب القفز بالوزن.",
    tipEn: "In bent-over barbell rows, lock your torso angle and initiate with back muscles without bouncing with the knees.",
  },
  {
    id: 143,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "احرص على استخدام مثبتات الأوزان (Collars/Clips) على البار دائماً لمنع انزلاق الأقراص واختلال التوازن المفاجئ.",
    tipEn: "Always use barbell collars/clips to prevent plates from shifting and causing dangerous sudden imbalances.",
  },
  {
    id: 144,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "الاستطالة الثابتة (Static Stretching) تكون بعد التمرين فقط؛ القيام بها قبل التمرين يقلل القوة الانفجارية مؤقتاً.",
    tipEn: "Perform static stretching post-workout only; long static holds before lifting temporarily reduce peak strength.",
  },
  {
    id: 145,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "في تمرين الدبس (Dips)، انزل حتى يصبح الكوع بزاوية 90 درجة فقط وتجنب النزول المفرط لحماية أوتار الكتف الأمامية.",
    tipEn: "In parallel dips, lower until elbows reach 90°; avoid extreme deep dips that overstretch the anterior shoulder.",
  },
  {
    id: 146,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "التحكم بمسار البار العمودي المستقيم في السكوات والبنش برس يقلل من عزم الدوران المهدر ويزيد كفاءة الرفع.",
    tipEn: "Maintaining a straight vertical bar path in squats and bench minimizes wasted moment arms and maximizes power.",
  },
  {
    id: 147,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "تقوية عضلات أسفل الظهر وعضلات الجذع العميقة (Core) هي الدرع الحصين للوقاية من الانزلاق الغضروفي (الدسك).",
    tipEn: "Strengthening deep core and lower back musculature is your primary defense against lumbar disc herniation.",
  },
  {
    id: 148,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "إذا كنت تشعر بآلام متكررة في المرفق في تمارين الترايسبس، استبدل البار المستقيم بحبل الكيبل أو الدمبلز.",
    tipEn: "If experiencing elbow strain during triceps extensions, switch from straight bars to neutral-grip cables or dumbbells.",
  },
  {
    id: 149,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "التنفس المنتظم أثناء التمرين (الزفير مع دفع الوزن والشهيق مع النزول) يمنع الارتفاع الحاد في ضغط الدم والدوخة.",
    tipEn: "Consistent breathing (exhale on effort, inhale on lowering) prevents dangerous blood pressure spikes and lightheadedness.",
  },
  {
    id: 150,
    categoryAr: "التكنيك والسلامة",
    categoryEn: "Form & Joint Safety",
    tipAr: "التكنيك الصحيح ليس عائقاً أمام الأوزان الثقيلة، بل هو الأساس الوحيد الذي يمكنك من رفع أوزان قياسية مدى الحياة بأمان!",
    tipEn: "Strict form isn't a limitation; it is the only foundation that lets you lift personal records safely for a lifetime!",
  },

  // ── 6. حرق الدهون وخسارة الوزن الصحية (151 - 175) ─────────────────────
  {
    id: 151,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "تمارين المقاومة تحافظ على الكتلة العضلية التي تعتبر المحرك الأساسي لحرق السعرات أثناء الراحة (BMR).",
    tipEn: "Resistance training preserves muscle mass, which is the primary driver of your resting metabolic rate (BMR).",
  },
  {
    id: 152,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "النشاط البدني غير الرياضي (NEAT) مثل صعود الدرج والمشي اليومي يحرق سعرات تفوق حصة التمرين ذاتها على مدار اليوم.",
    tipEn: "Non-Exercise Activity Thermogenesis (NEAT) like walking and taking stairs burns more total daily calories than workouts.",
  },
  {
    id: 153,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "المشي لـ 8000 إلى 10,000 خطوة يومياً وسيلة مثبتة علمياً لحرق الدهون دون إرهاق الجهاز العصبي أو زيادة الجوع.",
    tipEn: "Walking 8,000 to 10,000 steps daily is a proven tool for sustainable fat loss without spiking hunger or fatigue.",
  },
  {
    id: 154,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "عجز السعرات المعتدل (300-500 سعرة يومياً) يضمن خسارة الدهون مع الحفاظ التام على العضلات والطاقة اليومية.",
    tipEn: "A moderate deficit (300-500 kcal daily) ensures steady fat loss while preserving muscle tissue and daily vitality.",
  },
  {
    id: 155,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "رفع نسبة البروتين أثناء فترة التنشيف يرفع التأثير الحراري للغذاء (TEF) ويمنع تفكك الألياف العضلية.",
    tipEn: "Increasing protein during a cut boosts the thermic effect of food (TEF) and protects lean muscle tissue.",
  },
  {
    id: 156,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "لا تعتمد على الميزان كمعيار وحيد؛ تراجع مقاسات الخصر ونسبة الدهون في فحص InBody هو المقياس الحقيقي.",
    tipEn: "Don't judge progress by the scale alone; dropping waist measurements and InBody fat percentage tell the true story.",
  },
  {
    id: 157,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "تمارين الكارديو منخفض الشدة (Zone 2 Cardio) تعتمد على أكسدة الدهون كمصدر طاقة رئيسي وتقوي شبكة الميتوكوندريا.",
    tipEn: "Zone 2 low-intensity steady-state cardio optimizes fat oxidation and expands mitochondrial density.",
  },
  {
    id: 158,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "شرب كوبين من الماء قبل الوجبات الرئيسية بـ 15 دقيقة يملأ المعدة ويقلل استهلاك السعرات التلقائي بنسبة 13%.",
    tipEn: "Drinking 2 glasses of water 15 minutes before meals increases fullness and naturally reduces calorie intake by 13%.",
  },
  {
    id: 159,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "تجنب حميات الحرمان القاسية (Crash Diets)؛ فهي تبطئ عملية الأيض وتسبب ارتداد الوزن السريع (Yo-Yo Effect).",
    tipEn: "Avoid extreme crash diets; they slow metabolic rate, trigger muscle loss, and cause rapid rebound weight gain.",
  },
  {
    id: 160,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "تمارين الهيت (HIIT) لمدة 15 دقيقة مرتين أسبوعياً خيار رائع لحرق السعرات وزيادة اللياقة القلبية في وقت قياسي.",
    tipEn: "15 minutes of HIIT twice weekly is a time-efficient way to elevate metabolic burn and cardiovascular fitness.",
  },
  {
    id: 161,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "استبدال السكر الأبيض ببدائل خالية من السعرات (مثل ستيفيا) يوفر مئات السعرات غير المحسوبة أسبوعياً.",
    tipEn: "Replacing table sugar with zero-calorie sweeteners like Stevia eliminates hundreds of hidden weekly calories.",
  },
  {
    id: 162,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "النوم الجيد يقلل الرغبة الشديدة في تناول السكريات والوجبات السريعة عبر ضبط هرموني اللبتين والجريلين.",
    tipEn: "Quality sleep regulates leptin and ghrelin, drastically reducing cravings for sugar and fast food.",
  },
  {
    id: 163,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "الدهون الحشوية حول البطن تستجيب بسرعة لتقليل السكريات المكررة والمواظبة على المشي وتمارين المقاومة.",
    tipEn: "Visceral belly fat responds rapidly to eliminating refined sugars, consistent walking, and weight training.",
  },
  {
    id: 164,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "أداء الكارديو بعد تمرين الحديد مباشرة يكون أكثر كفاءة في حرق الدهون لأن مخازن الجليكوجين تكون مستنفذة جزئياً.",
    tipEn: "Cardio after lifting is more efficient for fat burning as glycogen stores are already partially depleted.",
  },
  {
    id: 165,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "تناول الخضروات الورقية والسلطات الخضراء بكميات حرة يمنحك شبعاً عالياً بفضل حجمها الكبير وسعراتها المنخفضة.",
    tipEn: "Leafy green salads provide immense volume and micronutrients with virtually negligible caloric impact.",
  },
  {
    id: 166,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "لا يمكنك حرق الدهون من منطقة محددة عبر تمرينها (Spot Reduction)؛ خسارة الدهون تحدث بشكل كلي من كامل الجسم.",
    tipEn: "Spot reduction is a myth; you cannot selectively burn fat from one area by doing crunches or specific exercises.",
  },
  {
    id: 167,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "يوم إعادة التغذية (Refeed Day) كل أسبوع أو أسبوعين أثناء التنشيف يعيد تنشيط هرمون اللبتين ومخازن الطاقة.",
    tipEn: "A structured carb refeed day every 1-2 weeks restores leptin levels and fuels higher training intensity.",
  },
  {
    id: 168,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "خل التفاح الطبيعي المخفف بالماء مع الوجبات يبطئ إفراغ المعدة ويقلل القفزات الحادة في مستويات الإنسولين.",
    tipEn: "Diluted apple cider vinegar with meals slows gastric emptying and blunts post-prandial insulin surges.",
  },
  {
    id: 169,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "الصلصات والمايونيز والزيوت المضافة في المطاعم قد تضيف 400-600 سعرة دون أن تشعر؛ اطلب الصلصة جانباً دائماً.",
    tipEn: "Dressings, mayo, and restaurant cooking oils add 400-600 stealth calories; always ask for sauces on the side.",
  },
  {
    id: 170,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "معدل الخسارة الصحية الآمنة للدهون هو 0.5% إلى 1% من وزن جسمك أسبوعياً لضمان عدم خسارة العضلات.",
    tipEn: "A safe, sustainable fat loss rate is 0.5% to 1% of your body weight weekly to preserve lean muscle tissue.",
  },
  {
    id: 171,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "المشروبات الغازية الدايت خيار آمن ومثالي لإشباع الرغبة في الطعم الحلو دون إضافة غرام سكر واحد لنظامك.",
    tipEn: "Diet sodas are a helpful tool to satisfy sweet cravings during calorie deficits without adding calories.",
  },
  {
    id: 172,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "الاستحمام بالماء البارد يحفز الأنسجة الدهنية البنية (Brown Adipose Tissue) لزيادة توليد الحرارة وحرق السعرات.",
    tipEn: "Cold showers stimulate metabolically active brown fat (BAT) to generate thermogenesis and burn extra energy.",
  },
  {
    id: 173,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "قراءة الملصق الغذائي (Nutrition Facts) ومعرفة السعرات والبروتين في كل حصة يحميك من الخداع التسويقي للمنتجات.",
    tipEn: "Reading nutrition labels carefully protects you from deceptive marketing claims and hidden serving sizes.",
  },
  {
    id: 174,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "شرب القهوة السوداء صباحاً يرفع معدل الأيض بنسبة 3-11% ويزيد من إفراز الأحماض الدهنية في مجرى الدم.",
    tipEn: "Morning black coffee elevates metabolic rate by 3-11% and mobilizes fatty acids into the bloodstream.",
  },
  {
    id: 175,
    categoryAr: "حرق الدهون والنشاط",
    categoryEn: "Fat Loss & Activity",
    tipAr: "الصبر هو المفتاح؛ الدهون التي تراكمت في سنوات تحتاج أشهراً من الانضباط والتدرج لتختفي بشكل دائم وصحي.",
    tipEn: "Patience is key; body fat accumulated over years requires months of steady discipline to lose permanently.",
  },

  // ── 7. المكملات الغذائية والفيتامينات (176 - 200) ──────────────────────
  {
    id: 176,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "الكرياتين مونوهيدرات (3-5 غرام يومياً) هو المكمل الأكثر إثباتاً علمياً لزيادة القوة الانفجارية وتسريع تعويض مخازن ATP.",
    tipEn: "Creatine monohydrate (3-5g daily) is the most scientifically proven supplement to increase explosive power and replenish ATP stores.",
  },
  {
    id: 177,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكمل الواي بروتين (Whey Protein) وسيلة مريحة ونقية وسريعة لإكمال احتياجك اليومي من البروتين عالي الجودة.",
    tipEn: "Whey protein is a convenient, pure, fast-digesting tool to hit your daily target of high-quality complete protein.",
  },
  {
    id: 178,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "فيتامين D3 يدعم قوة العظام، والمناعة، وإنتاج التستوستيرون؛ تناوله مع وجبة تحتوي على دهون لامتصاص مثالي.",
    tipEn: "Vitamin D3 supports bone density, immunity, and testosterone; take it with a fat-containing meal for best absorption.",
  },
  {
    id: 179,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكمل أوميغا 3 (بجرعة 1000-2000 ملغ من EPA + DHA) يقلل التهابات المفاصل ويحسن صحة القلب والأوعية الدموية.",
    tipEn: "Omega-3 fish oil (1000-2000mg combined EPA+DHA) suppresses joint inflammation and protects cardiovascular health.",
  },
  {
    id: 180,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "الزنك والمغنيسيوم (ZMA) ليلاً يعززان جودة النوم العميق ويحسنان تعافي الجهاز العصبي بعد التمارين الشاقة.",
    tipEn: "Zinc and Magnesium (ZMA) before bed support deep restorative sleep and neuromuscular recovery.",
  },
  {
    id: 181,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكمل البيتا ألانين (Beta-Alanine) يرفع مستويات الكارنوزين في العضلات ويؤخر الإحساس بالتعب في المجموعات الطويلة.",
    tipEn: "Beta-Alanine boosts intramuscular carnosine levels, buffering acidity and delaying fatigue in high-rep sets.",
  },
  {
    id: 182,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "الكافيين (3-6 ملغ لكل كغ من وزنك) قبل التمرين بـ 45 دقيقة يرفع التركيز الذهني والقدرة على رفع أوزان أثقل.",
    tipEn: "Caffeine (3-6mg per kg) 45 minutes pre-workout sharpens focus and enhances neuromuscular force output.",
  },
  {
    id: 183,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكمل السيترولين مالات (L-Citrulline Malate 6-8g) يرفع أكسيد النيتريك (NO) ويزيد من ضخ الدم والأكسجين للعضلات.",
    tipEn: "L-Citrulline Malate (6-8g) boosts nitric oxide, dramatically enhancing blood flow, vascularity, and muscle pumps.",
  },
  {
    id: 184,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكملات الفيتامينات المتعددة (Multivitamins) تعتبر شبكة أمان غذائية لسد أي نقص في المعادن الدقيقة في حميتك.",
    tipEn: "A high-quality multivitamin acts as nutritional insurance to cover micronutrient gaps in your daily diet.",
  },
  {
    id: 185,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "فيتامين K2 يعمل بتناغم مع فيتامين D3 لتوجيه الكالسيوم مباشرة إلى العظام والأسنان ومنع ترسبه في الشرايين.",
    tipEn: "Vitamin K2 works synergistically with D3 to direct calcium into bones and teeth rather than arterial walls.",
  },
  {
    id: 186,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكمل الجلوتامين (L-Glutamine) يدعم صحة بطانة الأمعاء والمناعة خاصة خلال فترات التنشيف القاسية.",
    tipEn: "L-Glutamine supports intestinal mucosal integrity and immune function, especially during hard cutting phases.",
  },
  {
    id: 187,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكملات الكولاجين مع فيتامين C تدعم مرونة الأوتار والأربطة والغضاريف وتقلل من آلام المفاصل المزمنة.",
    tipEn: "Collagen peptides paired with Vitamin C support tendon and ligament tensile strength and joint comfort.",
  },
  {
    id: 188,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "فيتامينات ب المركبة (B-Complex) ضرورية لتحويل الكربوهيدرات والبروتينات والدهون إلى طاقة خلوية قابلة للاستخدام.",
    tipEn: "B-Complex vitamins are essential enzymatic cofactors for converting carbs, fats, and protein into cellular ATP.",
  },
  {
    id: 189,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "الأشواغاندا (KSM-66 Ashwagandha) تساعد على خفض مستويات الكورتيزول المرتفعة وتحسين جودة النوم والراحة النفسية.",
    tipEn: "KSM-66 Ashwagandha reduces chronically elevated cortisol and fosters deeper sleep and mental calmness.",
  },
  {
    id: 190,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكمل الكازين (Casein Protein) هو البروتين الأنسب قبل النوم بفضل هضمه البطيء على مدار 6-8 ساعات.",
    tipEn: "Micellar casein protein is the optimal pre-bed shake, slowly releasing amino acids over 6-8 hours.",
  },
  {
    id: 191,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكملات الإلكترولايتات (الصوديوم، البوتاسيوم، الكالسيوم، المغنيسيوم) تمنع الهبوط العضلي والدوخة في التمارين المكثفة.",
    tipEn: "Electrolyte supplements (sodium, potassium, magnesium) prevent muscle cramping and lightheadedness in hard workouts.",
  },
  {
    id: 192,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "إنزيمات الهضم (Digestive Enzymes) مفيدة للمتدربين في فترات التضخيم لتسهيل امتصاص الوجبات الضخمة دون انتفاخ.",
    tipEn: "Digestive enzyme complexes help athletes in bulking phases absorb large meals comfortably without gut distress.",
  },
  {
    id: 193,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "الكرياتين لا يحتاج إلى مرحلة تحميل (Loading Phase) إجبارية؛ 5 غرامات يومياً باستمرار تحقق نفس النتيجة في 3 أسابيع.",
    tipEn: "Creatine loading is optional; taking 5g daily consistently fully saturates muscle stores within 3 weeks without GI distress.",
  },
  {
    id: 194,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكمل الجلوكوزامين والكوندرويتين يدعم تزييت المفاصل وتخفيف الاحتكاك لرافعي الأوزان الثقيلة.",
    tipEn: "Glucosamine and Chondroitin support joint cartilage hydration and reduce friction in heavy lifters.",
  },
  {
    id: 195,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "البروتين المعزول (Whey Isolate) هو الخيار الأفضل لمن يعانون من حساسية اللاكتوز أو اضطرابات الحليب.",
    tipEn: "Whey Isolate undergoes microfiltration to remove almost all lactose and fat, ideal for sensitive stomachs.",
  },
  {
    id: 196,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "الكروميوم بيكولينات (Chromium) يساعد في تحسين حساسية الإنسولين وتنظيم مستويات السكر والرغبة في الحلويات.",
    tipEn: "Chromium picolinate enhances insulin sensitivity and assists in managing blood sugar and sugar cravings.",
  },
  {
    id: 197,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مكملات الطاقة (Pre-workout) وسيلة دعم رائعة للأيام المرهقة، لكن تجنب الاعتماد اليومي المستمر عليها لتفادي التعود.",
    tipEn: "Pre-workouts are great for low-energy days, but cycle them periodically to avoid caffeine receptor tolerance.",
  },
  {
    id: 198,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "مستخلص الشاي الأخضر (EGCG) يعزز مضادات الأكسدة ويدعم التمثيل الغذائي وأكسدة الدهون بشكل طبيعي.",
    tipEn: "Green tea extract (EGCG) provides strong antioxidant defense and subtly supports metabolic fat oxidation.",
  },
  {
    id: 199,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "تذكر دائماً: المكملات اسمها 'مكملات'؛ هي تكمل نظاماً غذائياً ممتازاً وتدريباً منتظماً ولا تعوض التقصير فيهما أبداً!",
    tipEn: "Remember: Supplements are meant to 'supplement' a dialed-in diet and solid training; they never replace fundamentals!",
  },
  {
    id: 200,
    categoryAr: "المكملات والفيتامينات",
    categoryEn: "Supplements & Vitamins",
    tipAr: "استشر مدربك وأخصائي التغذية في Nasaq Gym لتحديد المكملات المناسبة لأهدافك الدقيقة وصحتك العامة بأعلى كفاءة!",
    tipEn: "Consult your Nasaq Gym trainer and nutritionist to tailor the exact supplement stack for your specific goals!",
  },
];

/**
 * Returns today's fitness tip based on day of year.
 */
export function getDailyTip(date: Date = new Date()): DailyTip {
  const startOfYear = new Date(date.getFullYear(), 0, 1);
  const diffTime = date.getTime() - startOfYear.getTime();
  const dayOfYear = Math.floor(diffTime / (1000 * 60 * 60 * 24));
  const index = Math.abs(dayOfYear) % DAILY_FITNESS_TIPS.length;
  return DAILY_FITNESS_TIPS[index];
}
