import * as React from "react";

declare module "lucide-react" {
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
    color?: string;
    strokeWidth?: string | number;
  }

  export type LucideIcon = React.ForwardRefExoticComponent<
    Omit<LucideProps, "ref"> & React.RefAttributes<SVGSVGElement>
  >;

  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const Users: LucideIcon;
  export const Hourglass: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Check: LucideIcon;
  export const X: LucideIcon;
  export const Loader2: LucideIcon;
  export const Calendar: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const Clock: LucideIcon;
  export const Trophy: LucideIcon;
  export const Building2: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const User: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Sparkles: LucideIcon;
  export const MapPin: LucideIcon;
  export const Award: LucideIcon;
  export const Bell: LucideIcon;
  export const BellOff: LucideIcon;
  export const BellRing: LucideIcon;
  export const Settings: LucideIcon;
  export const Search: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const Plus: LucideIcon;
  export const Minus: LucideIcon;
  export const Trash2: LucideIcon;
  export const Edit: LucideIcon;
  export const Filter: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const Info: LucideIcon;
  export const Shield: LucideIcon;
  export const Lock: LucideIcon;
  export const Unlock: LucideIcon;
  export const Dumbbell: LucideIcon;
  export const Activity: LucideIcon;
  export const Heart: LucideIcon;
  export const ShoppingBag: LucideIcon;
  export const Utensils: LucideIcon;
  export const Coffee: LucideIcon;
  export const LogOut: LucideIcon;
  export const Menu: LucideIcon;
  export const Play: LucideIcon;
  export const Pause: LucideIcon;
  export const Flame: LucideIcon;
  export const Zap: LucideIcon;
  export const Target: LucideIcon;
  export const Layers: LucideIcon;
  export const BarChart2: LucideIcon;
  export const LineChart: LucideIcon;
  export const PieChart: LucideIcon;
  export const FileText: LucideIcon;
  export const Camera: LucideIcon;
  export const Upload: LucideIcon;
  export const Download: LucideIcon;
  export const Share2: LucideIcon;
  export const QrCode: LucideIcon;
  export const CreditCard: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Percent: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const Square: LucideIcon;
  export const ArrowUpDown: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const XCircle: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const Sparkle: LucideIcon;
  export const ChevronDownCircle: LucideIcon;
  export const CircleAlert: LucideIcon;
  export const CircleCheck: LucideIcon;
  export const CircleX: LucideIcon;
  export const Copy: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Moon: LucideIcon;
  export const Sun: LucideIcon;
  export const Globe: LucideIcon;
  export const Compass: LucideIcon;
  export const Scale: LucideIcon;
  export const Ruler: LucideIcon;
  export const PercentCircle: LucideIcon;
  export const Key: LucideIcon;
}
